### ISSUE TITLE
Hook onto "ready" to avoid an issue with Compendium Folders

### ISSUE THREAD

**Issue by jessev14** [schultzcole/FVTT-Context-Convenience#3]
Very minor issue, but if both Context Convenience and Compendium Folders are enabled, the "Show/Hide all scenes in navigation bar" context menu item for scenes is shown for all folders:
![image](https://user-images.githubusercontent.com/68755874/114775675-913b1180-9d3f-11eb-9d86-7bd66e88ec1b.png)

Changing the Hook to "ready" instead of "init" appears to fix the issue (making Context Convenience "load" after Compendium Folders does its thing).

`- enso#0361`

**Comment by schultzcole** [comment]
Hmm, strange, thanks for the report.

**Comment by schultzcole** [comment]
Looks like this is a bug in Compendium Folders, I've created an issue for it on the compendium folders repo: https://github.com/earlSt1/vtt-compendium-folders/issues/67
